### ISSUE TITLE
ClamAV - permission denied on amavis tmp dir

### ISSUE THREAD

**Issue by starfoxx82** [docker-mailserver/docker-mailserver#1691]
## Context

Hi, I have the same problem like the closed issue no #1353 I've installed the mailserver on an kubernetes cluster and want to use the integrated ClamAV service for scanning. with (ENABLE_CLAMAV=1). 

### *What* is affected by this bug?
The mails will not be scanned by ClamAV. It generate an permission denied error log message

### *When* does this occur?
on running the application.

## *How* do we replicate the issue?

1. Install [(like wiki)](https://github.com/tomav/docker-mailserver/wiki/Using-in-Kubernetes)
2. send a mail from existing user to himself
3. see logs

## Actual Behavior

On an incoming email, this is writes in the logs:

> run_av (ClamAV-clamd) FAILED - unexpected , output="/var/lib/amavis/tmp/amavis-20201117T091752-00289-lTvNEEz7/parts: lstat() failed: Permission denied. ERROR\n"
> amavis[289]: (00289-01) (!)ClamAV-clamd av-scanner FAILED: CODE(0x55dda70f2a50) unexpected , output="/var/lib/amavis/tmp/amavis-20201117T091752-00289-lTvNEEz7/parts: lstat() failed: Permission denied. ERROR\n" at (eval 98) line 951.
> amavis[289]: (00289-01) (!)WARN: all primary virus scanners failed, considering backups

## Expected behavior (i.e. solution)

ClamAV should be able to analyze the emails without permission problems

## Your Environment

* Amount of RAM available: 8GB
* Mailserver version used: latest
* Docker version used: 19.03.13
* kubernetes version used: v1.19.3
* Environment settings relevant to the config:

## System
A kubernetes Cluster with an NFS pv

### pv.yaml
```
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mail-storage
  labels:
    type: local
  namespace: mailserver
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: xxx.xxx.xxx.xxx
    path: "/srv/nfs/kubedata/smtp/mail-storage"
```

### pvc.yaml
```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mail-storage-claim
  namespace: mailserver
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 500Mi
```

### configmap.yaml

```
data:
  ONE_DIR: "1"
```

### deployment.yaml
```
          - name: data
            mountPath: /var/mail
            subPath: data
          - name: data
            mountPath: /var/mail-state
            subPath: state
          - name: data
            mountPath: /var/log/mail
            subPath: log

        - name: data
          persistentVolumeClaim:
            claimName: mail-storage-claim
```

### NFS

And when I do ls -aln /var/lib/amavis/tmp/, I get this :
> drwxrwx--- 4 112 114 4096 Nov 17 10:21 .
> drwxr-x--- 8 112 114 4096 Nov 17 10:19 ..
> drwxr-x--- 3 112 114 4096 Nov 17 10:20 amavis-20201117T092012-00283-H7KnOmih
> drwxr-x--- 3 112 114 4096 Nov 17 10:21 amavis-20201117T092102-00282-5WnlwIhO

and on the NFS server i do ls -aln /srv/nfs/kubedata/smtp/mail-storage/state/lib-amavis/tmp, I get this:

> drwxrwx--- 4 112 114 4096 Nov 17 10:21 .
> drwxr-x--- 8 112 114 4096 Nov 17 10:19 ..
> drwxr-x--- 3 112 114 4096 Nov 17 10:20 amavis-20201117T092012-00283-H7KnOmih
> drwxr-x--- 3 112 114 4096 Nov 17 10:21 amavis-20201117T092102-00282-5WnlwIhO

**Comment by aendeavor** [comment]
Alright. Although I have _some_ experience with K8S, remotely trying to find the issue is hard. I hope someone has an idea. As you opened this issue, I'll close the other one again. Good luck!

**Comment by erik-wramner** [comment]
If you have a test cluster I would suggest trying one thing at a time. Specifically get rid of the NFS server and use a simpler mount option. If that works you know it is NFS-related (which I suspect).

**Comment by aendeavor** [comment]
This issue is marked as stale. Please report back. Otherwise this issue is closed due to inactivity.

**Comment by starfoxx82** [comment]
I have to try this out. I will write my realizations soon.

**Comment by starfoxx82** [comment]
i changed my configuration to the following:

### pv.yaml
```
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-mail-storage
  labels:
    type: local
  namespace: mailserver
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/srv/kubedata/smtp/mail-storage"
```
### pvc.yaml
```
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: local-mail-storage-claim
  namespace: mailserver
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
```

### deployment.yaml

```
      volumes:
        - name: config
          configMap:
            name: mailserver.config
        - name: opendkim-keys
          secret:
            secretName: mailserver.opendkim.keys
        - name: data
          persistentVolumeClaim:
            claimName: local-mail-storage-claim
        - name: tmp-files
          emptyDir: {}
```

### Log Output

it looks so good :-)


> Dec  3 08:10:05 pod amavis[901]: (00901-01) ESMTP :10024 /var/lib/amavis/tmp/amavis-20201203T081005-00901-QST18qWr: <testuser@example.com> -> <testuser@example.com> SIZE=15638 BODY=8BITMIME Received: from smtp.example.com ([127.0.0.1]) by localhost (smtp.example.com [127.0.0.1]) (amavisd-new, port 10024) with ESMTP for <testuser@example.com>; Thu,  3 Dec 2020 08:10:05 +0000 (UTC)
> Dec  3 08:10:06 pod amavis[901]: (00901-01) Checking: reZIr_MEOf9x [10.244.1.1] <testuser@example.com> -> <testuser@example.com>
> Dec  3 08:10:06 pod amavis[901]: (00901-01) p004 1 Content-Type: multipart/mixed
> Dec  3 08:10:06 pod amavis[901]: (00901-01) p005 1/1 Content-Type: multipart/alternative
> Dec  3 08:10:06 pod amavis[901]: (00901-01) p001 1/1/1 Content-Type: text/plain, 7bit, size: 27, SHA1 digest: f248aa114c26563c3c7b4ace89029e00b0a4478a
> Dec  3 08:10:06 pod amavis[901]: (00901-01) p002 1/1/2 Content-Type: text/html, 7bit, size: 232, SHA1 digest: 3353047c46e80f04e6a30de7f7c4285980d81389
> Dec  3 08:10:06 pod amavis[901]: (00901-01) p003 1/2 Content-Type: application/vnd.oasis.opendocument.text, base64, size: 10398, SHA1 digest: 05559cbe7d783dcf4f3cecf1a2c89cafc2108280, name: Testfile.odt
> ...


### NFS - exports
```
/srv/nfs/kubedata    192.168.17.0/24(rw,insecure,sync,no_subtree_check,no_root_squash)
```

**Comment by aendeavor** [comment]
I'm glad it works now. As expected, a configuration error - probably not the first or only done in K8S :D

I will close this issue as it has been solved. Other can now come across your solution, Thank you!:)

**Comment by starfoxx82** [comment]
It is only functional on local hostPath storage configuration on kubernetes. But the nfs problem still persists :-|

**Comment by aendeavor** [comment]
I understand. Then this needs to be re-opened.

**Comment by Jantek** [comment]
I can confirm that it is not working as long as I use NFS for the state-volume inside a Docker swarm.

**Comment by aendeavor** [comment]
Alright. But have you tried to apply the `user-patches.sh` script to patch the permissions? Or is there a fix inside the `start-mailserver.sh`?

**Comment by Jantek** [comment]
No. Did I miss something?

**Comment by aendeavor** [comment]
Yeah, but you could set them to a value that works for you with NFS, I guess

**Comment by Jantek** [comment]
Permissions without NFS:
```
root@mail:/# ls -la /var/lib/amavis/tmp/
total 28
drwxrwx--- 7 amavis amavis 4096 Jan 14 09:45 .
drwxr-x--- 8 amavis amavis 4096 Jan 14 09:22 ..
drwxr-x--- 3 amavis amavis 4096 Jan 13 14:16 amavis-20210113T141648-00698-4zmT6M6e
```
```
/var/lib/amavis/tmp/amavis-20210113T141648-00698-4zmT6M6e:
total 32
drwxr-x--- 3 amavis amavis  4096 Jan 13 14:16 .
drwxrwx--- 7 amavis amavis  4096 Jan 14 09:45 ..
-rw-r----- 1 amavis amavis 16497 Jan 13 14:41 email.txt
drwxr-x--- 2 amavis amavis  4096 Jan 14 09:49 parts
```
and with NFS:
```
root@mail:/var/lib/amavis/tmp# ls -la
total 96
drwxrwx--- 24 amavis amavis 4096 Jan 13 14:11 .
drwxr-x---  8 amavis amavis 4096 Jan 14 10:03 ..
drwxr-x---  3 amavis amavis 4096 Jan 12 21:14 amavis-20210112T211448-00800-UvdLy5dq
```
```
amavis-20210112T211448-00800-UvdLy5dq:
total 16
drwxr-x---  3 amavis amavis 4096 Jan 12 21:14 .
drwxrwx--- 24 amavis amavis 4096 Jan 13 14:11 ..
-rw-r-----  1 amavis amavis 1087 Jan 12 21:44 email.txt
drwxr-x---  2 amavis amavis 4096 Jan 12 21:46 parts
```
It is possible for the amavis user to write to the ```parts```-subdirs in NFS mode
```
sudo -u clamav touch parts/test-c; sudo -u amavis touch parts/test-a; ls -la parts/
```
```
touch: cannot touch 'parts/test-c': Permission denied
total 8
drwxr-x--- 2 amavis amavis 4096 Jan 14 10:08 .
drwxr-x--- 3 amavis amavis 4096 Jan 14 10:08 ..
-rw-r--r-- 1 amavis amavis    0 Jan 14 10:08 test-a
```

**Comment by Jantek** [comment]
If I mount a local volume to the ```tmp```-subdir it works too.

**Comment by aendeavor** [comment]
Maybe a `chown` and or `chmod` in `user-patches.sh` could help here?

**Comment by Jantek** [comment]
The permissions are the same, aren't they? Is it correct, that only the user ```amavis``` got write permissions to the ```parts```-subdirs?

> Permissions without NFS:
> 
> ```
> root@mail:/# ls -la /var/lib/amavis/tmp/
> total 28
> drwxrwx--- 7 amavis amavis 4096 Jan 14 09:45 .
> drwxr-x--- 8 amavis amavis 4096 Jan 14 09:22 ..
> drwxr-x--- 3 amavis amavis 4096 Jan 13 14:16 amavis-20210113T141648-00698-4zmT6M6e
> ```
> 
> ```
> /var/lib/amavis/tmp/amavis-20210113T141648-00698-4zmT6M6e:
> total 32
> drwxr-x--- 3 amavis amavis  4096 Jan 13 14:16 .
> drwxrwx--- 7 amavis amavis  4096 Jan 14 09:45 ..
> -rw-r----- 1 amavis amavis 16497 Jan 13 14:41 email.txt
> drwxr-x--- 2 amavis amavis  4096 Jan 14 09:49 parts
> ```
> 
> and with NFS:
> 
> ```
> root@mail:/var/lib/amavis/tmp# ls -la
> total 96
> drwxrwx--- 24 amavis amavis 4096 Jan 13 14:11 .
> drwxr-x---  8 amavis amavis 4096 Jan 14 10:03 ..
> drwxr-x---  3 amavis amavis 4096 Jan 12 21:14 amavis-20210112T211448-00800-UvdLy5dq
> ```
> 
> ```
> amavis-20210112T211448-00800-UvdLy5dq:
> total 16
> drwxr-x---  3 amavis amavis 4096 Jan 12 21:14 .
> drwxrwx--- 24 amavis amavis 4096 Jan 13 14:11 ..
> -rw-r-----  1 amavis amavis 1087 Jan 12 21:44 email.txt
> drwxr-x---  2 amavis amavis 4096 Jan 12 21:46 parts
> ```
> 
> It is possible for the amavis user to write to the `parts`-subdirs in NFS mode
> 
> ```
> sudo -u clamav touch parts/test-c; sudo -u amavis touch parts/test-a; ls -la parts/
> ```
> 
> ```
> touch: cannot touch 'parts/test-c': Permission denied
> total 8
> drwxr-x--- 2 amavis amavis 4096 Jan 14 10:08 .
> drwxr-x--- 3 amavis amavis 4096 Jan 14 10:08 ..
> -rw-r--r-- 1 amavis amavis    0 Jan 14 10:08 test-a
> ```

**Comment by aendeavor** [comment]
I don't actually know - I guess there's a reason, yes. But you could change the group ownership with a new group for all necessary involved parties?

**Comment by aendeavor** [comment]
Could be an issue for the NFS side too. **Have you set `noone` and `nogroup` for the host volume side**? This was necessary when using Kubernetes - I guess it could be true for Swarm as well.
