### ISSUE TITLE
docs: ARC with Rspamd for forwarded emails

### ISSUE THREAD

**Issue by Mygod** [docker-mailserver/docker-mailserver#3759]
### Context

Authenticated Received Chain (ARC) reduces bouncing of forwarded emails. See #3642.

### Description

Have an easy switch or a guide to enable ARC in DMS.

### Alternatives

Currently it seems possible to enable it through rspamd with a lot of manual tinkering (still testing?): https://github.com/docker-mailserver/docker-mailserver/issues/3642#issuecomment-1879911247

OpenARC is another alternative but doesn't seem quite good: https://github.com/trusteddomainproject/OpenARC/issues/157

### Applicable Users

Users that forward emails with DMS.

### Are you going to implement it?

Yes, because I know the probability of someone else doing it is low and I can learn from it.

### What are you going to contribute?

I could PR a guide to the wiki.

**Comment by georglauterbach** [comment]
I think we can easily integrate an ENV like `RSPAMD_ENABLE_ARC` (or something similar), if the config really is just 3 lines - or, make it a default even?

**Comment by polarathene** [comment]
Other mail projects like DMS have this feature already setup with rspamd, so you could likely refer to their source for what they're doing 😎

**Comment by georglauterbach** [comment]
## Overview

1. @Mygod provided his current additional configuration:

    ```ini
    sign_local = false;
    allow_hdrfrom_mismatch = true;
    use_domain = "recipient";
    ```

2. Here is [`mailcow`s configuration](https://github.com/mailcow/mailcow-dockerized/blob/master/data/conf/rspamd/local.d/arc.conf):

    ```ini
    # If false, messages with empty envelope from are not signed
    allow_envfrom_empty = true;
    # If true, envelope/header domain mismatch is ignored
    allow_hdrfrom_mismatch = true;
    # If true, multiple from headers are allowed (but only first is used)
    allow_hdrfrom_multiple = false;
    # If true, username does not need to contain matching domain
    allow_username_mismatch = false;
    # If false, messages from authenticated users are not selected for signing
    sign_authenticated = false;
    # Default path to key, can include '$domain' and '$selector' variables
    path = "/data/dkim/keys/$domain.dkim";
    # Default selector to use
    selector = "dkim";
    # If false, messages from local networks are not selected for signing
    sign_local = false;
    # Symbol to add when message is signed
    symbol = "ARC_SIGNED";
    # Whether to fallback to global config
    try_fallback = true;
    # Domain to use for DKIM signing: can be "header" or "envelope"
    use_domain = "recipient";
    # Whether to normalise domains to eSLD
    use_esld = false;
    # Whether to get keys from Redis
    use_redis = true;
    # Hash for DKIM keys in Redis
    key_prefix = "DKIM_PRIV_KEYS";
    # Selector map
    selector_prefix = "DKIM_SELECTORS";
    sign_inbound = true;
    use_domain_sign_inbound = "recipient";
    ```

3. Comparing to my currently running DMS instance (no explicit ARC configuration happening here):

    ```console
    root@mail:/# rspamadm configdump arc
    *** Section arc ***
    sign_networks [
        "127.2.4.7",
    ]
    sign_authenticated = false;
    use_esld = true;
    selector = "arc";
    allow_envfrom_empty = true;
    allow_hdrfrom_multiple = false;
    sign_inbound = true;
    sign_local = false;
    sign_symbol = "ARC_SIGNED";
    use_domain = "recipient";
    allow_hdrfrom_mismatch = true;
    use_redis = false;
    allow_username_mismatch = false;
    key_prefix = "ARC_KEYS";
    try_fallback = true;
    
    *** End of section arc ***
    ```

4. The [official Rspamd configuration of the ARC modules](https://github.com/rspamd/rspamd/blob/master/conf/modules.d/arc.conf):

    ```ini
    # If false, messages with empty envelope from are not signed
    allow_envfrom_empty = true;
    # If true, envelope/header domain mismatch is ignored
    allow_hdrfrom_mismatch = true;
    # If true, multiple from headers are allowed (but only first is used)
    allow_hdrfrom_multiple = false;
    # If true, username does not need to contain matching domain
    allow_username_mismatch = false;
    # If false, messages from authenticated users are not selected for signing
    sign_authenticated = false;
    # Default path to key, can include '$domain' and '$selector' variables
    path = "/data/dkim/keys/$domain.dkim";
    # Default selector to use
    selector = "dkim";
    # If false, messages from local networks are not selected for signing
    sign_local = false;
    # Symbol to add when message is signed
    symbol = "ARC_SIGNED";
    # Whether to fallback to global config
    try_fallback = true;
    # Domain to use for DKIM signing: can be "header" or "envelope"
    use_domain = "recipient";
    # Whether to normalise domains to eSLD
    use_esld = false;
    # Whether to get keys from Redis
    use_redis = true;
    # Hash for DKIM keys in Redis
    key_prefix = "DKIM_PRIV_KEYS";
    # Selector map
    selector_prefix = "DKIM_SELECTORS";
    sign_inbound = true;
    use_domain_sign_inbound = "recipient";
    ```

## Current Status Quo

It seems all the changes @Mygod applied are already defaults. The way I understood this issue is that @Mygod stated they had to add the configuration posted explicitly. @Mygod did you match `path = "/data/dkim/keys/$domain.dkim";` for the path to the DKIM keys? I guess the ARC module still needs access to the keys, and we'd need to provide the path explicitly..

**Comment by Mygod** [comment]
Ah I see I haven't actually enabled the module. I believe I've mistaken gmail's arc headers as rspamd.

**Comment by georglauterbach** [comment]
I think you will need to provide `path` explicitly. The configuration is similar to [DKIM](https://rspamd.com/doc/modules/dkim_signing.html). This should probably do the trick (I hope)... At the moment, Rspamd evaluates ARC properly already. Testing whether Rspamd adds an ARC header would be done by having DMS relay an email and check on the final receiver's side whether DMS added ARC headers.

**Comment by Mygod** [comment]
I copied the `domain` session from `dkim_signing` to `arc.conf` and restarted DMS. I didn't see anything changed in the ARC headers in my gmail client. 🤔

**Comment by georglauterbach** [comment]
> I copied the `domain` section from `dkim_signing` to `arc.conf` and restarted DMS. I didn't see anything changed in the ARC headers in my gmail client. 🤔

Did DMS forward an e-mail from another mail server to your GMail account?

**Comment by Mygod** [comment]
Yep. Gmail -> my server -> Gmail.

**Comment by georglauterbach** [comment]
I don't know at the moment whether copying the whole `domain` section works.. I guess ARC only needs the public key? Never worked with ARC before

**Comment by Mygod** [comment]
I did `docker-compose down && docker-compose up -d`.

**Comment by Mygod** [comment]
I managed to make it work now (I think). Somehow `sign_local = true;` is also needed or the arc module would refuse to sign. I updated https://github.com/docker-mailserver/docker-mailserver/issues/3642#issuecomment-1879911247 with the config.

Before: (this is presumably gmail's auth result)
![image](https://github.com/docker-mailserver/docker-mailserver/assets/3511321/fc91909f-df23-4512-b724-b3d5a6255a83)

After:
![image](https://github.com/docker-mailserver/docker-mailserver/assets/3511321/cf9cd4a2-dc50-4b5c-b6c9-8282cbdbb0dc)

**Comment by Mygod** [comment]
Not according to this: https://github.com/docker-mailserver/docker-mailserver/blob/aba218e6d7f30fbf4717178581c3e04537bea178/docs/content/config/best-practices/dkim_dmarc_spf.md?plain=1#L152

**Comment by georglauterbach** [comment]
> Not according to this: https://github.com/docker-mailserver/docker-mailserver/blob/aba218e6d7f30fbf4717178581c3e04537bea178/docs/content/config/best-practices/dkim_dmarc_spf.md?plain=1#L152

Can you be more specific, please?:)

**Comment by Mygod** [comment]
I was trying to say that I followed this tutorial and that's why I had this `sign_local` enabled. Probably should add `sign_authenticated = true` as well. :)

I don't remember my Docker setup. It's probably default other than enabling `ip6tables` I think?

**Comment by georglauterbach** [comment]
> I was trying to say that I followed this tutorial and that's why I had this `sign_local` enabled. Probably should add `sign_authenticated = true` as well. :)

👍🏼

> I don't remember my Docker setup. It's probably default other than enabling `ip6tables` I think?

And there we go - that's very likely the reason :D If the default 64NAT is applied, then the message appears as if it is coming from a local network (Docker's), hence the requirement. Please note that this may also be the reason your SPF checks fail - the origin IP is not correct when mail servers connect to your instance via IPv6. (There are a million other reasons SPF could not check out; the usual advice I give to people: don't use IPv6 😆).

**Comment by georglauterbach** [comment]
Alright - I guess ARC works pretty much out of the box except for

1. `sign_local` when 64NAT is active (but this also breaks SPF, i.e., it should be resolved by the user)
2. `sign_authenticated` is probably a good idea
3. the domain section of DKIM signing should be in the ARC configuration as well

Did I miss anything @Mygod?

**Comment by Mygod** [comment]
LGTM. 👍

**Comment by georglauterbach** [comment]
We can look into this when #3778 is completed, which itself is a subtask of #3630. Any help is appreciated.

**Comment by dustinmoris** [comment]
> Yep. Gmail -> my server -> Gmail.

@Mygod How did you set up the forwarding from DMS to Gmail? I set up Rspamd with ARC in my DMS and from my limited testing the ARC headers are being added but my emails which are being forwarded to Gmail are still bouncing. I use Mailgun as a relay though, which unfortunately I have to do because port 25 is blocked for outgoing traffic in Google Cloud.

Could you share a bit more details on your setup which seems to work? For example how did you set up the forwarding? I am using `postfix-virtual.cf` alias rules for that. Is there a different way which I could try that might work?

**Comment by polarathene** [comment]
> My issue was that I had to configure relay settings through a config file rather than the ENV vars. I needed to set these vars in order for it to work with Mailgun

You likely won't need to worry about that as much when v14 is out. Quite a few relay host feature support issues were resolved:

https://github.com/docker-mailserver/docker-mailserver/blob/849293f88c8a5faebbe2c704badae92b923b2ac5/CHANGELOG.md?plain=1#L52

https://github.com/docker-mailserver/docker-mailserver/blob/849293f88c8a5faebbe2c704badae92b923b2ac5/CHANGELOG.md?plain=1#L98-L101

You'd want to go with the **`DEFAULT_RELAY_HOST` ENV**, however this will **only properly configure from v14** IIRC. Our current `edge` version docs for the relay host feature page + the relay section at our ENV docs page were also rewritten accordingly.

Here's the location of the config settings in your screenshot to show that we handle that for you 👍 

https://github.com/docker-mailserver/docker-mailserver/blob/849293f88c8a5faebbe2c704badae92b923b2ac5/target/scripts/helpers/relay.sh#L94-L101

https://github.com/docker-mailserver/docker-mailserver/blob/849293f88c8a5faebbe2c704badae92b923b2ac5/target/postfix/main.cf#L56

[`smtp_sasl_mechanism_filter`](https://www.postfix.org/postconf.5.html#smtp_sasl_mechanism_filter) should not need to be set.

**Comment by dustinmoris** [comment]
@polarathene That is fantastic, thank you for the information, I'm looking forward to v14!

**Comment by Mygod** [comment]
I think my set up is still not quite right. I am still getting some bounced emails...

```
Mar 22 01:16:14 sparta postfix/smtp[3272020]: 3B9BA58B0: to=<mygmail@gmail.com>, orig_to=<myemail@mydomain.com>, relay=gmail-smtp-in.l.google.com[74.125.199.26]:25, delay=2.6, delays=1.7/0.01/0.18/0.7, dsn=5.7.26, status=bounced (host gmail-smtp-in.l.google.com[74.125.199.26] said: 550-5.7.26 This mail has been blocked because the sender is unauthenticated. 550-5.7.26 Gmail requires all senders to authenticate with either SPF or DKIM. 550-5.7.26  550-5.7.26  Authentication results: 550-5.7.26  DKIM = did not pass 550-5.7.26  SPF [sender server host] with ip: [my MX server IP] = did not 550-5.7.26 pass 550-5.7.26  550-5.7.26  For instructions on setting up authentication, go to 550 5.7.26  https://support.google.com/mail/answer/81126#authentication r3-20020a62e403000000b006e73e2f50b3si1418318pfh.193 - gsmtp (in reply to end of DATA command))
```

**Comment by dustinmoris** [comment]
@Mygod Did you set up dkim signing via Rspamd as well?

Your error message suggests you might have not done it or misconfigured it?

> Gmail requires all senders to authenticate with either SPF or DKIM

My `dkim_signing.conf` looks as following:

```
  dkim_signing.conf: |
    enabled = true;

    symbol = "DKIM_SIGNED";

    try_fallback = true;

    sign_authenticated = true;
    sign_local = true;

    allow_envfrom_empty = true;
    allow_hdrfrom_mismatch = false;
    allow_hdrfrom_multiple = false;
    allow_username_mismatch = false;

    use_domain = "header";
    use_redis = false;
    use_esld = true;
    check_pubkey = false;

    selector = "mail";
    path = "/tmp/docker-mailserver/rspamd/dkim/$domain/$selector.private";
```

Then I have mounted it like so:

```
- name: files
  subPath: dkim_signing.conf
  mountPath: /etc/rspamd/override.d/dkim_signing.conf
  readOnly: true
```

**Comment by Mygod** [comment]
I think docker-mailserver supports configuring dkim_signing already. `rspamadm configdump dkim_signing` also shows that mine is enabled.

**Comment by Mygod** [comment]
After some debugging, I see the email in question only supports SPF but not DKIM (this was sent by an external server). I wonder if ARC could be helpful at all for getting this email through gmail...

**Comment by Mygod** [comment]
Hmm this might be relevant. My mail server is attaching `ARC-Authentication-Results: i=1; <mail server>; none`. This seems wrong.

**Comment by Mygod** [comment]
```
2024-03-25 12:05:14 #504(rspamd_proxy) <78845d>; proxy; rspamd_url_text_extract: got empty text part
2024-03-25 12:05:19 #504(rspamd_proxy) <78845d>; proxy; rspamd_redis_connected: skip obtaining bayes tokens for BAYES_SPAM of classifier bayes: not enough learns 0; 200 required
2024-03-25 12:05:19 #504(rspamd_proxy) <78845d>; proxy; rspamd_redis_connected: skip obtaining bayes tokens for BAYES_HAM of classifier bayes: not enough learns 0; 200 required
2024-03-25 12:05:19 #504(rspamd_proxy) <78845d>; proxy; rspamd_task_write_log: id: <CANnZoVCUrDBAo4BHzP1Z3uAU0orbrotEoX3K1nedKvFwyVNg6g@mail.gmail.com>, qid: <374C03DE>, ip: 172.19.0.1, from: <sender@gmail.com>, (default: F (no action): [-0.10/11.00] [MIME_GOOD(-0.10){multipart/alternative;text/plain;},ARC_NA(0.00){},ARC_SIGNED(0.00){my.domain:s=mail:i=1;},DBL_FAIL(0.00){mail-io1-xd29.google.com:query timed out;},FREEMAIL_ENVFROM(0.00){gmail.com;},FREEMAIL_FROM(0.00){gmail.com;},FROM_EQ_ENVFROM(0.00){},FROM_HAS_DN(0.00){},MID_RHS_MATCH_FROMTLD(0.00){},MIME_TRACE(0.00){0:+;1:+;2:~;},MISSING_XM_UA(0.00){},PREVIOUSLY_DELIVERED(0.00){me@my.domain;},RCPT_COUNT_ONE(0.00){1;},RCVD_COUNT_ONE(0.00){1;},RCVD_TLS_LAST(0.00){},SURBL_MULTI_FAIL(0.00){mail-io1-xd29.google.com:query timed out;},TO_DN_NONE(0.00){},TO_MATCH_ENVRCPT_ALL(0.00){}]), len: 2564, time: 5311.532ms, dns req: 3, digest: <810c9593919c0610cafe486a8ac19889>, rcpts: <me@my.domain>, mime_rcpts: <me@my.domain>
```

My logs look wrong too. `rspamd` is getting query timed out. My container does seem to have network connectivity though.

**Comment by Mygod** [comment]
I am still seeing ARC not being applied in some cases, more specifically, if the sender passes SPF but does not have DKIM, ARC fails for some reason. Gmail simply bounces the forwarded email, and in Microsoft Outlook I see this:
```
ARC-Authentication-Results: i=2; mx.microsoft.com 1; spf=softfail; dmarc=none action=none; dkim=none (message not signed); arc=fail (47)
```

Other emails with DKIM have `arc=pass` as expected. How should I debug this? 🤔

**Comment by georglauterbach** [comment]
Is this possibly expected behavior? I mean, if there is no DKIM, can ARC actually work at all?

**Comment by Mygod** [comment]
Hmm I'm not sure but I thought it was supposed to help. Microsoft's `ARC-Seal` also reports `cv=fail` so maybe there's something wrong with the signature?

```
ARC-Seal: i=2; a=rsa-sha256; s=arcselector9901; d=microsoft.com; cv=fail; b=...
```

**Comment by georglauterbach** [comment]
The example you posted in https://github.com/docker-mailserver/docker-mailserver/issues/3759#issuecomment-2084082801 failed SPF, DKIM and DMARC. I'd guess ARC is not supposed to work then...

**Comment by georglauterbach** [comment]
[This](https://docs.plesk.com/en-US/obsidian/administrator-guide/mail/antispam-tools/dkim-spf-and-dmarc-protection-and-arc-support.59433/#enabling-arc-support) seems to indicate DKIM (or at least the DNS record) is a requirement for ARC to work.

**Comment by Mygod** [comment]
@georglauterbach Yes but that's the downstream validation result. Upstream result has SPF pass but missing DKIM and DMARC.
```
ARC-Authentication-Results: i=1;
	my.mailserver.com;
	dkim=none;
	spf=pass (omitted);
	dmarc=none
```

**Comment by Mygod** [comment]
> [This](https://docs.plesk.com/en-US/obsidian/administrator-guide/mail/antispam-tools/dkim-spf-and-dmarc-protection-and-arc-support.59433/#enabling-arc-support) seems to indicate DKIM (or at least the DNS record) is a requirement for ARC to work.

> Note: For the ARC signatures to be valid, the DNS records required for DKIM to work must be configured properly for the domain hosting the forwarding mail account.

I think it is saying that the domain hosting the forwarding mail needs to have DKIM, which I have. I am unsure if it is required for the sender to have working DKIM. (To be honest, if ARC requires DKIM on the sender then ARC seems a bit pointless?)

**Comment by Mygod** [comment]
I'm not saying this because I saw this documented anywhere. I just think that if the original email is already signed with DKIM then we can already know the authenticity of the email, right?

**Comment by polarathene** [comment]
> I just think that if the original email is already signed with DKIM then we can already know the authenticity of the email, right?

https://en.wikipedia.org/wiki/Authenticated_Received_Chain

> _Authenticated Received Chain (ARC) is an [email](https://en.wikipedia.org/wiki/Email) authentication system designed to **allow an intermediate mail server** like a mailing list or forwarding service to **sign an email's original authentication results.**_
>_This allows a receiving service to validate an email when the email's [SPF](https://en.wikipedia.org/wiki/Sender_Policy_Framework) and [DKIM](https://en.wikipedia.org/wiki/DKIM) records **are rendered invalid by an intermediate server's processing.**_

and

> _However, a strict [DMARC](https://en.wikipedia.org/wiki/DMARC) policy **may block legitimate emails** sent through a mailing list or forwarder, as the [DKIM](https://en.wikipedia.org/wiki/DKIM) signature will be **invalidated if the message is modified, such as by adding a subject tag or footer**, and the SPF check will either fail (if the forwarder didn't change the [bounce address](https://en.wikipedia.org/wiki/Bounce_address)) or be aligned with the mailing list domain and **not with the message author's domain** (unless the mailing list [rewrites the From: header field](https://en.wikipedia.org/wiki/DMARC#From:_rewriting).)_

> ARC was devised to solve this problem by giving **intermediate servers a way to sign the original message's validation results.** Even if the SPF and DKIM validation fail, the** receiving service can choose to validate the ARC chain**. If it indicates that the original message passed the SPF and DKIM checks, and the **only modifications were made by intermediaries trusted by the receiving service**, the receiving service may choose to accept the email.

---

It seems the above was roughly already understood in this discussion, but quoting with bolded emphasis for when ARC is relevant. The wiki entry also notes that it's up to the receiver to place trust in the ARC validation, but for the most part you're providing validation on any modifications to the forwarded mail such that it still allows for SPF and DKIM checks to pass validation despite the intermediary server that delivered it.

A good use-case where ARC is probably helpful is the [scenario described in this discussion](https://github.com/orgs/docker-mailserver/discussions/3965), where an intermediary receives the mail to forward to a private instance for storage purposes. However that complicates validation on SPF/DKIM AFAIK which would fail, so their approach was to blindly trust anything sent from the intermediary, skipping those security checks.

That discussion was summarized into a guide for our v14 docs, you can presently [view that on our `edge` docs here](https://docker-mailserver.github.io/docker-mailserver/edge/examples/use-cases/external-relay-only-mailserver/) for reference if it's of interest.

If the intermediary was instead a DMS instance and used ARC, then the private DMS instance should be able to perform the proper security checks on the forwarded mail if it was configured correctly.

**Comment by Mygod** [comment]
Reading [Google's recommendations](https://support.google.com/a/answer/175365?hl=en), they also seem to recommend adding "forwarding headers" such as "an X-Forwarded-For: or X-Forwarded-To: message header". How would one achieve that?

(Also I checked that when Microsoft Outlook forwards email, it also changes the `Return-Path` so that SPF would pass verification. I wonder if there is a way to do that here too.)

**Comment by Mygod** [comment]
It seems Gmail is still bouncing hardfail domains with ARC. 🤔 

```postfix/smtp: to=<myemail@gmail.com>, orig_to=<mymail@domain.com>, relay=gmail-smtp-in.l.google.com[2607:...]:25, dsn=5.7.26, status=bounced (host gmail-smtp-in.l.google.com[2607:...] said:
550-5.7.26 The MAIL FROM domain [hardfail.com] has an SPF record with a
550-5.7.26 hard fail policy (-all) but it fails to pass SPF checks with the ip:
550-5.7.26 [myip]. To best protect our users from spam and 550-5.7.26 phishing, the message has been blocked. For instructions on setting
550-5.7.26 up authentication, go to
550 5.7.26  https://support.google.com/mail/answer/81126#authentication - gsmtp (in reply to end of DATA command))
```

**Comment by georglauterbach** [comment]
Sorry, but I'm currently extremely low on time due to work. Of you find a solution, let me know, and we'll try to get it into the image.

**Comment by Mygod** [comment]
Oh apparently I haven't enabled `ENABLE_SRS=1` yet. Giving that a go now...

**Comment by georglauterbach** [comment]
@Mygod please provide a short list (or a PR for that matter) of the things you did to enable ARC. I feel like we should extend the documentation a bit, but functionality-wise, DMS is ready for ARC.

**Comment by Mygod** [comment]
Here's instructions: https://github.com/docker-mailserver/docker-mailserver/issues/3642#issuecomment-1879911247. My current `arc.conf`:
 ```
domain {
    domain.name {
        path = "/tmp/docker-mailserver/rspamd/dkim/rsa-2048-mail-domain.name.private.txt";
        selector = "mail";
    }
    // add more...
}
sign_local = true;
sign_authenticated = true;
```

(Also should enable `ENABLE_SRS=1` but that's unrelated to arc.)

**Comment by Nimon77** [comment]
Looks like this setup does not sign random forwarded email, maybe a bad configuration on my side, I expect it to work like that :
```
sender (random) |           forwarder          |          recipient          |
                |  Seal with forwarder.tld i=1 | Seal with recipient.tld i=2 |
```
but what I see from recipient side is `ARC-Seal: i=1; s=mail; d=recipient.tld`

Do you have any idea ? 🤔

**Comment by polarathene** [comment]
Haven't given much thought on the topic, but there was a recent discussion [here](https://github.com/orgs/docker-mailserver/discussions/4311) where DMS was receiving mail with ARC and presumably DMS having ARC support would resolve it.
